shinyUI(navbarPage("Respones Curve Explorer",
#===============================================
# ==========  Map Explorer ==========#
tabPanel("Map Explorer",

helpText("The response curves that are generated by holding each predictor constant at the mean.",
   "are displayed in black",
   "clicking on any map pixel will generate the response curves",
   "holding each predictor constant at the value under the pixel rather than the mean."),
# Insert the right number of plot output objects into the web page
fluidRow(
  column(4,
  wellPanel(
  plotOutput("map1", click = "plot_click",height="350px"),style="padding: 5px;"),style="padding: 5px;"),
  column(6,
  wellPanel(plotOutput("curves1",height="350px"),style="padding: 5px;"),style="padding: 5px;" )
  ),
conditionalPanel(length(modelLst)>1,
 fluidRow(
  column(4,
  wellPanel(
  plotOutput("map2", click = "plot_click",height="350px"),style="padding: 5px;"),style="padding: 5px;"),
  column(6,
  wellPanel(plotOutput("curves2",height="350px"),style="padding: 5px;"),style="padding: 5px;" )
  )
 ),
 conditionalPanel(length(modelLst)>2,
 fluidRow(
  column(4,
  wellPanel(
  plotOutput("map3", click = "plot_click",height="350px"),style="padding: 5px;"),style="padding: 5px;"),
  column(6,
  wellPanel(plotOutput("curves3",height="350px"),style="padding: 5px;"),style="padding: 5px;" )
  )
 ),
 conditionalPanel(length(modelLst)>3,
 fluidRow(
  column(4,
  wellPanel(
  plotOutput("map4", click = "plot_click",height="350px"),style="padding: 5px;"),style="padding: 5px;"),
  column(6,
  wellPanel(plotOutput("curves4",height="350px"),style="padding: 5px;"),style="padding: 5px;" )
  
  )
  )
),
#===============================================
# ==========  Slide Explorer ==========#
tabPanel("Slide Explorer",
helpText("Use the sliders to change the value that each predictor is held at in generating the response", 
         "curves once you are satisfied with your selections clicking \"add curves for current values\" will",
         "add these values in a new color to the plot."), 
actionButton("addVals", label = "add curves for current values"),
fluidRow(
lapply(1:length(dataLst),function(i){
column(1,uiOutput(paste0("slide",i)))
})),
fluidRow(
lapply(1:length(dataLst),function(i){
column(1,plotOutput(paste0("slideRsp",i),height=rspHgt))
}))

),

#===============================================
# ==========  Interaction ==========#
tabPanel("Interaction Tool",
helpText("Explore the interaction between two predictors in the model while holding",
   "all other predictors constant at the value",
   "specified by the sliders"),
sidebarPanel(  
            uiOutput("sliders"),                           
            width=2),                           
mainPanel(
  fluidRow(
    column(3,
        selectInput("FirstPredictor", choices=Variables,selected=Variables[1],label=h4("First Predictor"))),
    column(3,    
        selectInput("SecondPredictor", choices=Variables,selected=Variables[max(length(Variables),2)],label=h4("Second Predictor"))),
    column(3,    
        selectInput("Model", choices=c("All",unlist(modelLst)),label=h4("Model")))
   ),     
  wellPanel(
      plotOutput("interact"),
       sliderInput("phi", label = h4("phi"),
                                        min = 0, max = 90,value=35),
       sliderInput("theta", label = h4("theta"),
                                        min = 0, max = 360,value=300),
      width="100%",height="120%")                               
)
)


))